version: '3.7'

services:
  postgresql:
    image: postgres:${IMAGE_TAG:-10.5-alpine}
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    networks:
      net:
        aliases:
          - db
    volumes:
      - vol:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        delay: 10s
        window: 1m
      resources:
        limits:
          cpus: '2'
          memory: 128M
        reservations:
          memory: 103M

networks:
  net:
    name: tajinaste-net

volumes:
  vol:
    name: ${VOLUME_NAME:-postgresql-vol}
