version: '3.9'

services:
  tajinaste-database:
    image: ${IMAGE_NAME:-postgres}:${IMAGE_TAG:-14-alpine}
    environment:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    networks:
      tajinaste-net:
        aliases:
          - ${TAJINASTE_NET_ALIAS:-db}
    volumes:
      - data-vol:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-1m}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-64M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-16M}

networks:
  tajinaste-net:
    name: ${TAJINASTE_NET_NAME:-tajinaste-net}
    driver: ${TAJINASTE_NET_DRIVER:-overlay}
    attachable: ${TAJINASTE_NET_ATTACHABLE:-true}

volumes:
  data-vol:
    name: ${DATA_VOL_NAME:-tajinaste-database-vol}
    driver: local
    driver_opts:
      type: ${VOL_TYPE}
      o: addr=${VOL_ADDR},${VOL_OPTS}
      device: ${DATA_VOL_DEVICE:-:/tajinaste-database-vol/}
